DEPTH = ../..

include $(DEPTH)/config.mk

LIBRARY = Tao.PhysFs
DOCS = 1

SRCS = \
	AssemblyInfo.cs \
	Fs.cs \
	$(NULL)

CSFLAGS += /unsafe /doc:$(DOC_DEST)/$(LIBRARY).xml
	

include $(DEPTH)/rules.mk