
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = FogIndex
EXAMPLE_CATEGORY = Redbook

SRCS = \
	AssemblyInfo.cs \
	FogIndex.cs \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
