#region License
/*
MIT License
Copyright ©2003-2006 Tao Framework Team
http://www.taoframework.com
All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
#endregion License

using System;
using System.Collections;
using System.Collections.Specialized;
using System.IO;
using System.Reflection;
using System.Text.RegularExpressions;

namespace Tao.GlGenerator
{
    /// <summary>
    /// 
    /// </summary>
    public static class Common
    {
        #region Fields
        #endregion

        #region Private Methods

        internal static void WriteLicense(StreamWriter streamWriter)
        {
            streamWriter.WriteLine("#region License");
            streamWriter.WriteLine("/*");
            streamWriter.WriteLine("THIS FILE IS AUTOMATICALLY GENERATED");
            streamWriter.WriteLine("DO NOT EDIT BY HAND!!");
            streamWriter.WriteLine();
            streamWriter.WriteLine("MIT License");
            streamWriter.WriteLine("Copyright 2003-2006 Tao Framework Team");
            streamWriter.WriteLine("http://www.taoframework.com");
            streamWriter.WriteLine("All rights reserved.");
            streamWriter.WriteLine();
            streamWriter.WriteLine("Permission is hereby granted, free of charge, to any person obtaining a copy");
            streamWriter.WriteLine("of this software and associated documentation files (the \"Software\"), to deal");
            streamWriter.WriteLine("in the Software without restriction, including without limitation the rights");
            streamWriter.WriteLine("to use, copy, modify, merge, publish, distribute, sublicense, and/or sell");
            streamWriter.WriteLine("copies of the Software, and to permit persons to whom the Software is");
            streamWriter.WriteLine("furnished to do so, subject to the following conditions:");
            streamWriter.WriteLine();
            streamWriter.WriteLine("The above copyright notice and this permission notice shall be included in all");
            streamWriter.WriteLine("copies or substantial portions of the Software.");
            streamWriter.WriteLine();
            streamWriter.WriteLine("THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR");
            streamWriter.WriteLine("IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,");
            streamWriter.WriteLine("FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE");
            streamWriter.WriteLine("AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER");
            streamWriter.WriteLine("LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,");
            streamWriter.WriteLine("OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE");
            streamWriter.WriteLine("SOFTWARE.");
            streamWriter.WriteLine("*/");
            streamWriter.WriteLine("#endregion License");
        }

        internal static void WriteOpenBrace(StreamWriter streamWriter)
        {
            streamWriter.WriteLine("{");
        }

        internal static void WriteCloseBrace(StreamWriter streamWriter)
        {
            streamWriter.WriteLine("}");
        }

        internal static void WriteEmptyLine(StreamWriter streamWriter)
        {
            streamWriter.WriteLine();
        }

        #endregion
    }
}
