
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Lesson18
EXAMPLE_CATEGORY = NeHe

SRCS = \
	AssemblyInfo.cs \
	Lesson18.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/NeHe.Lesson18.Wall.bmp \
	$(NULL)

CSFLAGS += /target:winexe
REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.Platform.Windows.dll \
	System.Windows.Forms.dll \
	System.Drawing.dll \
	$(NULL)

include $(DEPTH)/rules.mk
