
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Simple
EXAMPLE_CATEGORY = PhysFsExamples

SRCS = \
	AssemblyInfo.cs \
	Simple.cs \
	$(NULL)

REFS = \
	Tao.PhysFs.dll \
	$(NULL)

include $(DEPTH)/rules.mk
