
DEPTH = ../..

include $(DEPTH)/config.mk

PROGRAM = Tao.PostProcess

SRCS = \
	AssemblyInfo.cs \
	AppMain.cs \
	BuildProcessor.cs \
	Options.cs \
	ReleaseBuildProcessor.cs \
	UsageHelp.cs \
	$(NULL)

include $(DEPTH)/rules.mk

