
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Qix
EXAMPLE_CATEGORY = NateRobbins

SRCS = \
	AssemblyInfo.cs \
	Qix.cs \
	Point.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
