
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Rectangles
EXAMPLE_CATEGORY = SdlExamples

SRCS = \
	AssemblyInfo.cs \
	Rectangles.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/SdlExamples.Rectangles.sound.ogg \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.Sdl.dll \
	$(NULL)

include $(DEPTH)/rules.mk
