
DEPTH = ../..

include $(DEPTH)/config.mk

LIBRARY = Tao.OpenAl

SRCS = \
	AssemblyInfo.cs \
	Al.cs \
	Alc.cs \
	Alut.cs \
	$(NULL)

CSFLAGS += /unsafe /doc:$(LIBRARY_DEST)/$(LIBRARY).xml

include $(DEPTH)/rules.mk
