
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Lesson08
EXAMPLE_CATEGORY = NeHe

SRCS = \
	AssemblyInfo.cs \
	Lesson08.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/NeHe.Lesson08.Glass.bmp \
	$(NULL)
	
CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.Platform.Windows.dll \
	System.Windows.Forms.dll \
	System.Drawing.dll \
	$(NULL)

include $(DEPTH)/rules.mk
