
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Lesson23
EXAMPLE_CATEGORY = NeHe

SRCS = \
	AssemblyInfo.cs \
	Lesson23.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/NeHe.Lesson23.BG.bmp \
	Data/NeHe.Lesson23.Reflect.bmp \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.Platform.Windows.dll \
	System.Windows.Forms.dll \
	System.Drawing.dll \
	$(NULL)

include $(DEPTH)/rules.mk
