
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Area
EXAMPLE_CATEGORY = NateRobbins

SRCS = \
	AssemblyInfo.cs \
	Area.cs \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
