
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Triangle
EXAMPLE_CATEGORY = GlfwExamples

SRCS = \
	AssemblyInfo.cs \
	Triangle.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.Glfw.dll \
	$(NULL)

include $(DEPTH)/rules.mk
