
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Gears
EXAMPLE_CATEGORY = GlfwExamples

SRCS = \
	AssemblyInfo.cs \
	Gears.cs \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.Glfw.dll \
	$(NULL)

include $(DEPTH)/rules.mk
