
DEPTH = ..

include $(DEPTH)/config.mk

DIRS = \
	DevIlExamples \
	GeWang \
	GlfwExamples \
	NateRobins \
	NeHe \
	OdeExamples \
	OpenAlExamples \
	Redbook \
	SdlExamples \
	$(NULL)

include $(DEPTH)/rules.mk
