
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = PickSquare
EXAMPLE_CATEGORY = Redbook

SRCS = \
	AssemblyInfo.cs \
	PickSquare.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
