
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = KeyTest
EXAMPLE_CATEGORY = GlfwExamples

SRCS = \
	AssemblyInfo.cs \
	KeyTest.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.OpenGl.dll \
	Tao.Glfw.dll \
	$(NULL)

include $(DEPTH)/rules.mk
