
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = SimpleExample
EXAMPLE_CATEGORY = DevIlExamples

SRCS = \
	AssemblyInfo.cs \
	SimpleExample.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/yinyangblue.gif \
	$(NULL)

REFS = \
	Tao.DevIl.dll \
	$(NULL)

include $(DEPTH)/rules.mk
