
DEPTH = ../..

include $(DEPTH)/config.mk

LIBRARY = Tao.OpenGl.ExtensionLoader
DOCS = 1

SRCS = \
	AssemblyInfo.cs \
	GlExtensionLoader.cs \
	$(NULL)

CSFLAGS += /doc:$(DOC_DEST)/$(LIBRARY).xml

include $(DEPTH)/rules.mk

