
DEPTH = ../..

include $(DEPTH)/config.mk

LIBRARY = Tao.OpenGl.ExtensionLoader

SRCS = \
	AssemblyInfo.cs \
	GlExtensionLoader.cs \
	$(NULL)

CSFLAGS += /doc:$(LIBRARY_DEST)/$(LIBRARY).xml

include $(DEPTH)/rules.mk

