
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Lesson02
EXAMPLE_CATEGORY = OpenAlExamples

SRCS = \
	AssemblyInfo.cs \
	Lesson02.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/OpenAlExamples.Lesson02.Footsteps.wav \
	$(NULL)

CSFLAGS += /target:exe

REFS = \
	Tao.OpenAl.dll \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
