
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = ListModes
EXAMPLE_CATEGORY = GlfwExamples

SRCS = \
	AssemblyInfo.cs \
	ListModes.cs \
	$(NULL)

CSFLAGS += /target:exe

REFS = \
	Tao.OpenGl.dll \
	Tao.Glfw.dll \
	$(NULL)

include $(DEPTH)/rules.mk
