
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Basic
EXAMPLE_CATEGORY = OdeExamples

SRCS = \
	AssemblyInfo.cs \
	Basic.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.Ode.dll \
	$(NULL)

include $(DEPTH)/rules.mk
