
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Lesson26
EXAMPLE_CATEGORY = NeHe

SRCS = \
	AssemblyInfo.cs \
	Lesson26.cs \
	$(NULL)

EXAMPLE_DATA = \
	Data/NeHe.Lesson26.Ball.bmp \
	Data/NeHe.Lesson26.Envroll.bmp \
	Data/NeHe.Lesson26.Envwall.bmp \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.Platform.Windows.dll \
	System.Windows.Forms.dll \
	System.Drawing.dll \
	$(NULL)

include $(DEPTH)/rules.mk
