
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Xform
EXAMPLE_CATEGORY = GeWang

SRCS = \
	AssemblyInfo.cs \
	Xform.cs \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
