
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = Mirror
EXAMPLE_CATEGORY = GeWang

SRCS = \
	AssemblyInfo.cs \
	Mirror.cs \
	$(NULL)

CSFLAGS += /unsafe

REFS = \
	Tao.OpenGl.dll \
	Tao.OpenGl.Glu.dll \
	Tao.FreeGlut.dll \
	$(NULL)

include $(DEPTH)/rules.mk
