
DEPTH = ../..

include $(DEPTH)/config.mk

PROGRAM = Tao.GlPostProcess

SRCS = \
	AssemblyInfo.cs \
	GlPostProcess.cs \
	$(NULL)

REFS = \
	Tao.OpenGl.ExtensionLoader.dll \
	$(NULL)

include $(DEPTH)/rules.mk

