
DEPTH = ../..

include $(DEPTH)/config.mk

LIBRARY = Tao.DevIl

SRCS = \
	AssemblyInfo.cs \
	Il.cs \
	Ilu.cs \
	Ilut.cs \
	$(NULL)

CSFLAGS += /doc:$(DOC_DEST)/$(LIBRARY).xml

include $(DEPTH)/rules.mk
