
DEPTH = ..

include $(DEPTH)/config.mk

# OpenGl.ExtensionLoader must come before GlPostProcess and OpenGl.
# PostProcess must come before SDL.
DIRS = \
	Tao.OpenGl.ExtensionLoader \
	Tao.GlPostProcess \
	Tao.OpenGl \
	Tao.OpenGl.Glu \
	Tao.Cg \
	Tao.DevIl \
	Tao.FreeGlut \
	Tao.Glfw \
	Tao.Ode \
	Tao.OpenAl \
	Tao.PostProcess \
	Tao.Sdl \
	Tao.Platform.Windows \
	$(NULL)

include $(DEPTH)/rules.mk
