
DEPTH = ../../..

include $(DEPTH)/config.mk

EXAMPLE = GfxPrimitives
EXAMPLE_CATEGORY = SdlExamples

SRCS = \
	AssemblyInfo.cs \
	GfxPrimitives.cs \
	$(NULL)

CSFLAGS += /target:winexe

REFS = \
	Tao.Sdl.dll \
	$(NULL)

include $(DEPTH)/rules.mk
